name: Release

on:
  release:
    types: [published]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Package with tox
        run: tox -e package
      - name: Publish Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          file: "dist/*.tar.gz;dist/*.whl;build/*.pex"
          release_id: ${{ github.event.release.tag_name }}
